# Generated by Django 5.2.12 on 2026-03-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid10Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('classificacao', models.CharField(blank=True, max_length=5)),
                ('descricao', models.CharField(max_length=500)),
                ('descricao_abreviada', models.CharField(blank=True, max_length=500)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('excluidos', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'CID-10 Categoria',
                'verbose_name_plural': 'CID-10 Categorias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CidOMorfologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comportamento', models.CharField(blank=True, max_length=8)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'CID-O Morfologia',
                'verbose_name_plural': 'CID-O Morfologias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SacMapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesao', models.CharField(blank=True, max_length=30)),
                ('parte_corpo_ossea_articular', models.CharField(blank=True, max_length=120)),
                ('parte_corpo_muscular', models.CharField(blank=True, max_length=120)),
                ('parte_corpo_tendinosa', models.CharField(blank=True, max_length=120)),
                ('parte_corpo_neurologica', models.CharField(blank=True, max_length=120)),
                ('membros_superiores', models.CharField(blank=True, max_length=120)),
                ('coluna', models.CharField(blank=True, max_length=120)),
                ('bacia', models.CharField(blank=True, max_length=120)),
                ('membros_inferiores', models.CharField(blank=True, max_length=120)),
                ('lateralidade', models.CharField(blank=True, max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'SAC Mapeamento',
                'verbose_name_plural': 'SAC Mapeamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_lesao', models.CharField(choices=[('Óssea', 'Óssea'), ('Articular', 'Articular'), ('Muscular', 'Muscular'), ('Tendinosa', 'Tendinosa'), ('Neurológica', 'Neurológica')], max_length=20)),
                ('origem_lesao', models.CharField(choices=[('Por Estresse', 'Por Estresse'), ('Traumática', 'Traumática'), ('Outra', 'Outra')], max_length=30)),
                ('estrutura_anatomica', models.CharField(max_length=120)),
                ('lateralidade', models.CharField(choices=[('Direita', 'Direita'), ('Esquerda', 'Esquerda'), ('Bilateral', 'Bilateral'), ('Não é o caso', 'Não é o caso')], max_length=20)),
                ('codigo_cid10', models.CharField(max_length=10)),
                ('codigo_cido', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_sred', models.BooleanField(default=False, editable=False)),
                ('cadete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='pessoal.militar')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_medicos', to='pessoal.profissionalsaude')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoMultidisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer_tecnico', models.TextField()),
                ('data_evolucao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='saude.atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='pessoal.profissionalsaude')),
            ],
            options={
                'ordering': ['-data_evolucao'],
            },
        ),
    ]
