# Generated by Django 5.2.12 on 2026-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaReferenciaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('SEM_ALTERACAO', 'Sem alteração'), ('FALHA', 'Falha')], max_length=20)),
                ('reset', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('arquivos_processados', models.JSONField(blank=True, default=list)),
                ('arquivos_alterados', models.JSONField(blank=True, default=list)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Carga de Referências',
                'verbose_name_plural': 'Histórico de Cargas de Referências',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaArquivoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=120, unique=True)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('primeira_carga_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_carga_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versão de Arquivo de Referência',
                'verbose_name_plural': 'Versões de Arquivos de Referência',
                'ordering': ['nome_arquivo'],
            },
        ),
    ]
