# Generated by Django 5.2.12 on 2026-03-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_cargareferenciahistorico_referenciaarquivoversao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid10categoria',
            name='record_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash do registro para detecção de mudanças', max_length=64),
        ),
        migrations.AddField(
            model_name='cidomorfologia',
            name='record_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash do registro para detecção de mudanças', max_length=64),
        ),
        migrations.AddField(
            model_name='sacmapeamento',
            name='record_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash do registro para detecção de mudanças', max_length=64),
        ),
        migrations.CreateModel(
            name='RecordChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(help_text='Nome da tabela (ex: Cid10Categoria, CidOMorfologia, SacMapeamento)', max_length=50)),
                ('registro_id', models.PositiveIntegerField(help_text='ID do registro alterado')),
                ('chave_registra', models.CharField(help_text='Chave única (ex: codigo CID-10)', max_length=120)),
                ('tipo_mudanca', models.CharField(choices=[('CRIADO', 'Criado'), ('ATUALIZADO', 'Atualizado'), ('INALTERADO', 'Inalterado')], max_length=12)),
                ('hash_anterior', models.CharField(blank=True, help_text='Hash anterior (vazio se CRIADO)', max_length=64)),
                ('hash_novo', models.CharField(help_text='Hash novo após mudança', max_length=64)),
                ('dados_alterados', models.JSONField(blank=True, default=dict, help_text='Campos que mudaram {campo: [anterior, novo]}')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historico_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_audits', to='saude.cargareferenciahistorico')),
            ],
            options={
                'verbose_name': 'Auditoria de Mudança de Registro',
                'verbose_name_plural': 'Auditorias de Mudanças de Registro',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tabela', 'registro_id'], name='saude_recor_tabela_63966f_idx'), models.Index(fields=['-criado_em'], name='saude_recor_criado__1dc105_idx')],
            },
        ),
    ]
