# Generated by Django 5.0.14 on 2026-03-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_cid10categoria_record_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='cid10_secundarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='classificacao_atividade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='conduta_terapeutica',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='disposicao_cadete',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='encaminhamentos_multidisciplinares',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='localizacao_lesao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='modalidade_esportiva',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='notas_clinicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='segmento_corporal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitar_exames_complementares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tfm_taf',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_atendimento',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Retorno', 'Retorno')], default='Inicial', max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_atividade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='codigo_cid10',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
