# Generated by Django 5.0.14 on 2026-03-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_atendimento_cid10_secundarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='exames_complementares',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
