# Generated by Django 5.0.14 on 2026-03-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_atendimento_exames_complementares'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='decisao_sred',
            field=models.CharField(blank=True, choices=[('S-RED Positivo', 'S-RED Positivo'), ('S-RED Negativo', 'S-RED Negativo')], default='', max_length=20),
        ),
    ]
