# Generated by Django 5.0.14 on 2026-03-20 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0006_atendimento_decisao_sred'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaudeReferenciaLesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tecido', models.CharField(db_index=True, max_length=30)),
                ('regiao_geral', models.CharField(db_index=True, max_length=120)),
                ('sub_regiao', models.CharField(db_index=True, max_length=120)),
                ('item_especifico', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Referência de Lesão',
                'verbose_name_plural': 'Referências de Lesões',
                'ordering': ['tipo_tecido', 'regiao_geral', 'sub_regiao', 'item_especifico'],
            },
        ),
        migrations.AddField(
            model_name='sacmapeamento',
            name='item_especifico_manual',
            field=models.CharField(blank=True, help_text='Item específico informado manualmente quando ausente na referência.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sacmapeamento',
            name='sub_regiao_manual',
            field=models.CharField(blank=True, help_text='Sub-região informada manualmente quando ausente na referência.', max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='saudereferencialesao',
            constraint=models.UniqueConstraint(fields=('tipo_tecido', 'regiao_geral', 'sub_regiao', 'item_especifico'), name='unique_referencia_lesao'),
        ),
        migrations.AddField(
            model_name='sacmapeamento',
            name='referencia_lesao',
            field=models.ForeignKey(blank=True, help_text='Referência normalizada da lesão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_mapeamentos', to='saude.saudereferencialesao'),
        ),
    ]
