# Generated by Django 5.2.12 on 2026-03-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0007_referencia_lesao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='referencia_lesao',
            field=models.ForeignKey(blank=True, help_text='Referência normalizada da lesão (preenchida automaticamente ao salvar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='saude.saudereferencialesao'),
        ),
    ]
