# Generated by Django 5.2.12 on 2026-03-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0008_atendimento_referencia_lesao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='estrutura_anatomica',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='origem_lesao',
            field=models.CharField(blank=True, choices=[('Por Estresse', 'Por Estresse'), ('Traumática', 'Traumática'), ('Outra', 'Outra')], default='', max_length=30),
        ),
    ]
