# Generated by Django 5.2.12 on 2026-03-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0009_alter_atendimento_estrutura_anatomica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_origem',
            field=models.ForeignKey(blank=True, help_text='Atendimento inicial que originou este retorno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos', to='saude.atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='medicamentoso',
            field=models.BooleanField(default=False, help_text='Tratamento medicamentoso prescrito.'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='decisao_sred',
            field=models.CharField(blank=True, choices=[('Investigação Pendente', 'Investigação Pendente'), ('Em Investigação', 'Em Investigação'), ('S-RED Positivo', 'S-RED Positivo'), ('S-RED Negativo', 'S-RED Negativo')], default='', max_length=30),
        ),
    ]
