# Generated by Django 5.2.12 on 2026-03-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_militar', models.CharField(max_length=30, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('posto_graduacao', models.CharField(blank=True, max_length=80)),
                ('arma_quadro_servico', models.CharField(blank=True, max_length=80)),
                ('curso', models.CharField(blank=True, max_length=120)),
                ('companhia', models.CharField(blank=True, max_length=80)),
                ('pelotao', models.CharField(blank=True, max_length=80)),
                ('is_instrutor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('Médico', 'Médico'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Nutricionista', 'Nutricionista'), ('Psicopedagogo', 'Psicopedagogo'), ('Estatístico', 'Estatístico')], max_length=40)),
                ('registro_profissional', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('militar', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_saude', to='pessoal.militar')),
            ],
            options={
                'verbose_name': 'Profissional de Saúde',
                'verbose_name_plural': 'Profissionais de Saúde',
            },
        ),
    ]
