# Generated by Django 5.2.12 on 2026-03-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='sexo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='militar',
            name='turma',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
