# Generated by Django 5.0.14 on 2026-03-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fracao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='funcao_instrutor',
            field=models.CharField(blank=True, choices=[('Comandante do Corpo de Cadetes', 'Comandante do Corpo de Cadetes'), ('Subcomandante do Corpo de Cadetes', 'Subcomandante do Corpo de Cadetes'), ('S1-CC', 'S1-CC'), ('Comandante de Curso', 'Comandante de Curso'), ('Comandante de Subunidade', 'Comandante de Subunidade'), ('Comandante de Pelotão', 'Comandante de Pelotão')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_guerra',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posto_graduacao',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
