# Generated by Django 5.0.14 on 2026-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_userprofile_fracao_userprofile_funcao_instrutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='ano',
            field=models.CharField(blank=True, choices=[('1º Ano', '1º Ano'), ('2º Ano', '2º Ano'), ('3º Ano', '3º Ano'), ('4º Ano', '4º Ano'), ('5º Ano', '5º Ano')], max_length=10),
        ),
        migrations.AddField(
            model_name='militar',
            name='nome_guerra',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
