# Generated by Django 5.2.12 on 2026-03-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_militar_ano_militar_nome_guerra'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Matrícula ou identificador alternativo para rastreabilidade anônima.', max_length=30),
        ),
    ]
